"""create video table

Revision ID: f4c1b03f7972
Revises: 
Create Date: 2025-06-30 03:15:13.216153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from database.models.video import ProcessingStatus

# revision identifiers, used by Alembic.
revision: str = 'f4c1b03f7972'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("id", sa.TEXT(), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("processing_status", sa.Enum(ProcessingStatus), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("videos")
    # ### end Alembic commands ###
